# https://docs.gradle.org/current/userguide/platforms.html
# Current issues:
# Idea highlight libs import as an issue because of https://github.com/gradle/gradle/issues/22797
# More about toml format:
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
official-mssql = "11.2.3.jre18"


[libraries]
official-mssql = { group = "com.microsoft.sqlserver", name = "mssql-jdbc", version.ref = "official.mssql" }
